build:
  build:
    image: kerneltime/vibauthor-and-go:0.5
    commands:
      - go get github.com/golang/lint/golint
      - make build

  fpm:
    privileged: true
    image: docker
    volumes:
      # Needed for creating docker images
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t vmware/fpm -f dockerfiles/Dockerfile.fpm . > /dev/null
    when:
      success: true

  package:
    image: vmware/fpm
    commands:
      - make deb rpm
    when:
      success: true

  test:
    image: kerneltime/vibauthor-and-go:0.5
    privileged: true
    environment:
      - GOVC_USERNAME=$$CI_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_ESX_IP
    commands:
      - export VM1=`govc vm.ip ubuntu`
      - export VM2=`govc vm.ip ubuntu-2`
      - ./drone-scripts/deploy-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
      - ./drone-scripts/testremote-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
    when:
      success: true

matrix:
  GO_VERSION:
    - 1.6

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: vmware/docker-vmdk-plugin
    tag:
      - "latest"
      - $$BRANCH-$$BUILD_NUMBER
    file: dockerfiles/Dockerfile.vmdk-plugin
    privileged: true
    storage_driver: overlay
    when:
      branch: master
  
  github_release:
    api_key: $$GITHUB_TOKEN
    files:
      - bin/*.deb
      - bin/*.rpm
      - bin/*.vib
      - bin/*.zip
    when:
      repo: vmware/docker-vmdk-plugin
      event: tag
