build:
  ci:
    privileged: true
    image: kerneltime/vibauthor-and-go:0.4
    volumes:
      # Needed for creating docker images
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GOVC_USERNAME=$$CI_VMWARE_ESX_USER
      - GOVC_PASSWORD=$$CI_VMWARE_ESX_PASS
      - GOVC_INSECURE=1
      - GOVC_URL=$$CI_ESX_IP
    commands:
      - export VM1=`govc vm.ip ubuntu`
      - export VM2=`govc vm.ip ubuntu-2`
      - make build
      - ./drone-scripts/deploy-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
      - make test
      - ./drone-scripts/testremote-wrapper.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: kerneltime/docker-vmdk-plugin
    tag:
      - "latest"
      - $$BRANCH-$$BUILD_NUMBER
    file: dockerfiles/Dockerfile.vmdk-plugin
    privileged: true
    storage_driver: overlay
    when:
      branch: master
