build:
  ci:
    privileged: true
    image: kerneltime/vibauthor-and-go:0.4
    volumes:
      # Needed for creating docker images
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GOVC_USERNAME=root
      - GOVC_PASSWORD=
      - GOVC_INSECURE=1
      - GOVC_URL=192.168.109.59
    commands:
      - export VM1=`govc vm.ip ubuntu`
      - export VM2=`govc vm.ip ubuntu-2`
      - make
      - make test
      - ./hack/setup.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null
      - ./hack/end2end.sh $GOVC_URL $VM1 $VM2 $$BUILD_NUMBER < /dev/null

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: kerneltime/docker-vmdk-plugin
    tag: latest
    file: Dockerfile.vmdk-plugin
    privileged: true
    storage_driver: overlay
    when:
      branch: master
