build:
  master:
    image: kerneltime/vibauthor-and-go:0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./logit.sh make
      - ./logit.sh "make test"
      - ./logit.sh "ping -c 1 192.168.109.2"
      - ./logit.sh "ssh $$CI_VMWARE_ESX_USER@192.168.109.2 ls"
    when :
      event: [push, tag]
      branch: master

  codereview:
    image: kerneltime/vibauthor-and-go:0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./logit.sh make
      - ./logit.sh "make test"
      - ./logit.sh "ping -c 1 192.168.109.2"
      - ./logit.sh "ssh $$CI_VMWARE_ESX_USER@192.168.109.2 ls"
    when :
      event: pull_request

  develop:
    image: kerneltime/vibauthor-and-go:0.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./logit.sh "make test"
    when :
      event: push
      branch: "!master"

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    image: casualjim/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: kerneltime/docker-vmdk-plugin
    tag: "$$BRANCH-$$BUILD_NUMBER"
    file: Dockerfile.vmdk-plugin.debug
    privileged: true
    storage_driver: overlay
    when:
      event: pull_request
  docker:
    image: casualjim/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: kerneltime/docker-vmdk-plugin
    tag: latest
    file: Dockerfile.vmdk-plugin
    privileged: true
    storage_driver: overlay
    when:
      branch: master
