site_name: Docker Volume Driver for vSphere
pages:
- Home: index.md
- Installation and Deployment: install.md
- Admin CLI: vmdkops-admin-cli-spec.md
- Docker Volume CLI: 
  - Basic commands: docker-volume-cli.md
  - Multiple Datastores: datastores.md
- Backend ESX Overview: 
  - 'Volume Layout': esx-overview.md
- Features:
  - 'Integration with vCenter': vcenter.md
  - 'VSAN Policy': vsan-policy.md
theme: readthedocs
google_analytics: ['UA-81413942-1', 'https://vmware.github.io/docker-volume-vsphere/']
